version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: hitime
      POSTGRES_PASSWORD: hitime_pw
      POSTGRES_DB: hitime
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hitime']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=hitime
      - DB_PASSWORD=hitime_pw
      - DB_NAME=hitime
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8080
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    ports:
      - '3000:3000'
      - '6006:6006' # Storybook
    volumes:
      - ./frontend:/app

volumes:
  db_data:
  redis_data: 